In [97]:
import numpy as np
import pandas as pd

In [99]:
df = pd.read_csv("https://raw.githubusercontent.com/suneel0101/lesson-plan/master/crunchbase_monthly_export.csv", na_values=' -   ')
df.head()

,permalink,name,homepage_url,category_list,market,funding_total_usd,status,country_code,state_code,region,city,funding_rounds,founded_at,founded_month,founded_quarter,founded_year,first_funding_at,last_funding_at,Unnamed: 18
0,/organization/canal-do-credito,Canal do Credito,http://www.canaldocredito.com.br,|Credit|Technology|Services|Finance|,Credit,"750,000",NaN,BRA,NaN,Rio de Janeiro,Belo Horizonte,1,NaN,NaN,NaN,NaN,1/1/10,1/1/10,NaN
1,/organization/waywire,#waywire,http://www.waywire.com,|Entertainment|Politics|Social Media|News|,Entertainment,"1,750,000",acquired,USA,NY,New York City,New York,1,6/1/12,2012-06,2012-Q2,2012.0,6/30/12,6/30/12,NaN
2,/organization/tv-communications,&TV Communications,http://enjoyandtv.com,|Games|,Games,"4,000,000",operating,USA,CA,Los Angeles,Los Angeles,2,NaN,NaN,NaN,NaN,6/4/10,9/23/10,NaN
3,/organization/rock-your-paper,'Rock' Your Paper,http://www.rockyourpaper.org,|Publishing|Education|,Education,"40,000",operating,EST,NaN,Tallinn,Tallinn,1,10/26/12,2012-10,2012-Q4,2012.0,8/9/12,8/9/12,NaN
4,/organization/in-touch-network,(In)Touch Network,http://www.InTouchNetwork.com,|Electronics|Guides|Coffee|Restaurants|Music|i...,Apps,"1,500,000",operating,GBR,NaN,London,London,1,4/1/11,2011-04,2011-Q2,2011.0,4/1/11,4/1/11,NaN

In [102]:
df.columns = df.columns.str.strip(' ')
df.columns

Index([u'permalink', u'name', u'homepage_url', u'category_list', u'market',
       u'funding_total_usd', u'status', u'country_code', u'state_code',
       u'region', u'city', u'funding_rounds', u'founded_at', u'founded_month',
       u'founded_quarter', u'founded_year', u'first_funding_at',
       u'last_funding_at'],
      dtype='object')

In [100]:
df.dropna(axis=1, how='all', inplace=True)
df.head()

,permalink,name,homepage_url,category_list,market,funding_total_usd,status,country_code,state_code,region,city,funding_rounds,founded_at,founded_month,founded_quarter,founded_year,first_funding_at,last_funding_at
0,/organization/canal-do-credito,Canal do Credito,http://www.canaldocredito.com.br,|Credit|Technology|Services|Finance|,Credit,"750,000",NaN,BRA,NaN,Rio de Janeiro,Belo Horizonte,1,NaN,NaN,NaN,NaN,1/1/10,1/1/10
1,/organization/waywire,#waywire,http://www.waywire.com,|Entertainment|Politics|Social Media|News|,Entertainment,"1,750,000",acquired,USA,NY,New York City,New York,1,6/1/12,2012-06,2012-Q2,2012.0,6/30/12,6/30/12
2,/organization/tv-communications,&TV Communications,http://enjoyandtv.com,|Games|,Games,"4,000,000",operating,USA,CA,Los Angeles,Los Angeles,2,NaN,NaN,NaN,NaN,6/4/10,9/23/10
3,/organization/rock-your-paper,'Rock' Your Paper,http://www.rockyourpaper.org,|Publishing|Education|,Education,"40,000",operating,EST,NaN,Tallinn,Tallinn,1,10/26/12,2012-10,2012-Q4,2012.0,8/9/12,8/9/12
4,/organization/in-touch-network,(In)Touch Network,http://www.InTouchNetwork.com,|Electronics|Guides|Coffee|Restaurants|Music|i...,Apps,"1,500,000",operating,GBR,NaN,London,London,1,4/1/11,2011-04,2011-Q2,2011.0,4/1/11,4/1/11

In [56]:
#make a dummy variable from the 'market' column
pd.get_dummies(df[' market ']).head()

,3D,3D Printing,3D Technology,Accounting,Active Lifestyle,Ad Targeting,Advanced Materials,Adventure Travel,Advertising,Advertising Exchanges,...,Web Hosting,Web Tools,Weddings,Wholesale,Wine And Spirits,Wireless,iOS,iPad,iPhone,mHealth
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [92]:
#Clean the funding_total_usd column (it's an 'object' and should be an integer)
df.dtypes

permalink               object
name                    object
homepage_url            object
category_list           object
 market                 object
 funding_total_usd     float64
status                  object
country_code            object
state_code              object
region                  object
city                    object
funding_rounds           int64
founded_at              object
founded_month           object
founded_quarter         object
founded_year           float64
first_funding_at        object
last_funding_at         object
Unnamed: 18            float64
dtype: object

In [91]:
df[' funding_total_usd '] = pd.to_numeric(df[' funding_total_usd '].str.replace(',', ''), errors='coerce')

In [95]:
#Create some pivots
pd.pivot_table(df, index = ' market ')

,funding_total_usd,Unnamed: 18,founded_year,funding_rounds
market,,,,
3D,9.189392e+06,NaN,2008.437500,1.588235
3D Printing,1.967000e+06,NaN,2012.166667,1.833333
3D Technology,NaN,NaN,2013.000000,1.000000
Accounting,1.989102e+07,NaN,2008.373134,2.200000
Active Lifestyle,4.100833e+06,NaN,2011.600000,1.666667
Ad Targeting,2.486977e+07,NaN,2008.722222,2.381818
Advanced Materials,5.550000e+07,NaN,2007.500000,2.000000
Adventure Travel,1.706032e+05,NaN,2010.600000,1.600000
Advertising,1.195821e+07,NaN,2008.321367,1.934026
Advertising Exchanges,2.648729e+07,NaN,2011.000000,2.666667
Advertising Networks,8.773903e+05,NaN,2010.900000,1.000000
Advertising Platforms,9.715235e+07,NaN,2007.636364,2.272727
Advice,4.504138e+06,NaN,2008.952381,1.500000
Aerospace,1.616990e+07,NaN,2010.526316,1.958333
Agriculture,1.115717e+07,NaN,2008.750000,2.400000
Algorithms,2.643819e+06,NaN,2010.000000,1.692308
All Markets,3.220442e+06,NaN,2005.411765,1.833333
All Students,5.884268e+07,NaN,2009.650000,1.776119
Alternative Medicine,6.200000e+06,NaN,2013.000000,1.000000
Alumni,2.156835e+06,NaN,2008.200000,1.666667
Analytics,1.187397e+07,NaN,2008.869186,2.053960
Android,7.603216e+06,NaN,2009.923483,1.870886
Angels,1.948246e+06,NaN,2008.500000,1.250000
Animal Feed,3.832500e+06,NaN,2011.666667,1.333333
App Marketing,7.128752e+06,NaN,2007.250000,1.475000
App Stores,6.060544e+06,NaN,2008.370370,1.888889
Application Performance Monitoring,2.009890e+07,NaN,2008.333333,3.333333
Application Platforms,2.433425e+07,NaN,2007.666667,2.166667
Apps,5.931559e+06,NaN,2010.348730,1.737991
Aquaculture,7.500000e+05,NaN,2013.000000,1.000000
...,...,...,...,...
Therapeutics,6.300000e+06,NaN,2013.000000,2.000000
Ticketing,5.259272e+06,NaN,2006.600000,1.200000
Tourism,9.143131e+06,NaN,2012.500000,1.333333
Toys,3.600000e+05,NaN,2009.000000,4.000000
Tracking,7.705000e+06,NaN,2010.666667,3.500000
Trading,4.000000e+04,NaN,2013.000000,1.000000
Transportation,5.499976e+06,NaN,2009.250000,1.086957
Travel,1.495166e+07,NaN,2008.313953,1.486111
Travel & Tourism,3.799846e+06,NaN,2009.571429,1.625000
User Experience Design,2.500000e+04,NaN,2014.000000,1.000000
Utilities,3.875395e+07,NaN,2007.250000,1.200000
Venture Capital,1.800000e+07,NaN,2011.000000,2.000000
Veterinary,NaN,NaN,NaN,1.000000
Video,5.450000e+06,NaN,2009.875000,1.000000
Video Games,2.182811e+06,NaN,2005.000000,1.375000
Video Streaming,1.250000e+06,NaN,2009.333333,1.000000
Video on Demand,6.389987e+06,NaN,2007.000000,4.000000
VoIP,1.175000e+07,NaN,1999.000000,1.000000
Web Design,5.400000e+06,NaN,2005.000000,1.000000
Web Development,9.167600e+06,NaN,2010.333333,1.500000
Web Hosting,2.738112e+07,NaN,2001.369004,1.755263
Web Tools,4.000000e+06,NaN,1998.000000,4.000000
Weddings,3.762500e+06,NaN,2013.000000,1.333333
Wholesale,1.260228e+06,NaN,2010.000000,1.000000
Wine And Spirits,1.910000e+06,NaN,2011.285714,1.142857
Wireless,1.961250e+07,NaN,2012.000000,1.000000
iOS,7.901242e+05,NaN,2011.000000,1.583333
iPad,1.850270e+06,NaN,2010.315789,1.550000
iPhone,2.372621e+06,NaN,2009.717949,1.243902
mHealth,1.219390e+05,NaN,2012.000000,1.500000